services:
  - type: web
    name: farahna
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
